// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQOmJJDZQc1CJ1Ms7jZIShR1S88aoszzo',
    appId: '1:885696725145:web:9dd24173e96ebfb441b808',
    messagingSenderId: '885696725145',
    projectId: 'react-native-app-31d60',
    authDomain: 'react-native-app-31d60.firebaseapp.com',
    databaseURL: 'https://react-native-app-31d60-default-rtdb.firebaseio.com',
    storageBucket: 'react-native-app-31d60.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHz0MX5nee1LYhG1jat5_FwLEjyP2U8rc',
    appId: '1:885696725145:android:ff2132f0893c74b341b808',
    messagingSenderId: '885696725145',
    projectId: 'react-native-app-31d60',
    databaseURL: 'https://react-native-app-31d60-default-rtdb.firebaseio.com',
    storageBucket: 'react-native-app-31d60.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMGppCvicQMxvSyFV_T0K-lAzWgU7s4n0',
    appId: '1:885696725145:ios:3f0d9f326185587f41b808',
    messagingSenderId: '885696725145',
    projectId: 'react-native-app-31d60',
    databaseURL: 'https://react-native-app-31d60-default-rtdb.firebaseio.com',
    storageBucket: 'react-native-app-31d60.appspot.com',
    androidClientId: '885696725145-ephffluf307k0rfvc582fgh32ph2v0k2.apps.googleusercontent.com',
    iosClientId: '885696725145-hgoh68hnrssmbkitt6gbvoarp7sqkpti.apps.googleusercontent.com',
    iosBundleId: 'com.example.greencircuit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMGppCvicQMxvSyFV_T0K-lAzWgU7s4n0',
    appId: '1:885696725145:ios:3f0d9f326185587f41b808',
    messagingSenderId: '885696725145',
    projectId: 'react-native-app-31d60',
    databaseURL: 'https://react-native-app-31d60-default-rtdb.firebaseio.com',
    storageBucket: 'react-native-app-31d60.appspot.com',
    androidClientId: '885696725145-ephffluf307k0rfvc582fgh32ph2v0k2.apps.googleusercontent.com',
    iosClientId: '885696725145-hgoh68hnrssmbkitt6gbvoarp7sqkpti.apps.googleusercontent.com',
    iosBundleId: 'com.example.greencircuit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQOmJJDZQc1CJ1Ms7jZIShR1S88aoszzo',
    appId: '1:885696725145:web:2a0b1ef8495c84a341b808',
    messagingSenderId: '885696725145',
    projectId: 'react-native-app-31d60',
    authDomain: 'react-native-app-31d60.firebaseapp.com',
    databaseURL: 'https://react-native-app-31d60-default-rtdb.firebaseio.com',
    storageBucket: 'react-native-app-31d60.appspot.com',
  );
}
